# __author__ = 'ilya_rubinshteyn'
# Guess the outputs that would be generated by each of the following program fragments, and then run to verify your results. Explain the differences.
#
# (a)
#
# for i in range(1, 11):
#
#     print (i*i)
#
# (b)
#
# for i in [1,3,5,7,9]:
#
#     print (i, ":", i**3)
#
# print (i)
#
# (c)
#
# x = 2
#
# y = 10
#
# for j in range(0, y, x):
#
#     print (j)
#
#     print (x + y)
#
# print ("done")
# (d)
#
# ans = 0
# for i in range(1, 9):
#
#     ans = ans + i*i
#
#     print (i)
# print (ans)
#
#
# What you need to hand in:
#
# BOTH your guess and actual results.
#
# (Note: Grades will be based on your efforts not your guesses are right or wrong at this time.)
#
#  Answer
# a) Guess: Will multiply i by i ten times.
#
# Actual: Multiplied i by i in range 1-11, so it multiplied 1*1, 2*2, 3*3, 4*4, etc... until 10*10.
#
#
#
# b) Guess: i is equal to 1, 3, 5, 7, 9 so it will print: 1**3, 3**3, 5**3, 7**3, 9**3, so output should be:
#
# "1 : 1"
#
# "3 : 27"
#
# "5 : 125"
#
# "7 : 343"
#
# "9 : 729"
#
# actual output:  difference i forgot about the final print of "i"
#
# 1 : 1
# 3 : 27
# 5 : 125
# 7 : 343
# 9 : 729
# 9
#
# c) guess: so since the loop is not properly written, you will get error when trying to run it. Loop should look like this:
# x = 2
#
# y = 10
#
# for j in range(0, y, x):
#
#     print j,
#
#     print x + y
# print "done"
# so in this case, j will print 2,4,6,8,10 and x+y will print 12.
#
# actual: IndentationError: unexpected indent
#
# actual result with correct loop format:
# 0
# 12
# 2
# 12
# 4
# 12
# 6
# 12
# 8
# 12
# done
#
# Impression: I did thought j would start printing with 2, and i didnt realize (x+y) will be printing until 8 was reached.
#
#
# d) guess: since:
#     i is 1,2,3,4,5,6,7,8
#
#
# ans = 64 final
# output will be:
#
# 1
# 2
# 3
# 4
# 5
# 6
# 7
# 8
# 64
#
# notes: i didnt account for new variable ans being added every time the loop is run.
#
# actual result:
#
#
#
# 1
# 2
# 3
# 4
# 5
# 6
# 7
# 8
# 204
#
#